# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/dscommerce
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Segurança e CORS
cors.origins=http://localhost:3000,http://localhost:5173

security.client-id=myclientid
security.client-secret=myclientsecret
security.jwt.duration=3600